//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Travel_Booking_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int adminid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string admin_password { get; set; }
    }
}
