//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Travel_Booking_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelrequest
    {
        public int requestid { get; set; }
        public Nullable<int> employeeid { get; set; }
        public string employeefirstname { get; set; }
        public string employeelastname { get; set; }
        public string employeeemail { get; set; }
        public string reasonfortravel { get; set; }
        public string flightneeded { get; set; }
        public string hotelneeded { get; set; }
        public string departurecity { get; set; }
        public string arrivalcity { get; set; }
        public Nullable<System.DateTime> departuredate { get; set; }
        public Nullable<System.TimeSpan> departuretime { get; set; }
        public string additionalinformation { get; set; }
        public string approvalstatus { get; set; }
        public string bookingstatus { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
