//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Travel_Booking_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelagent
    {
        public int agentid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string travel_agent_password { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
