//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Travel_Booking_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelrequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public travelrequest()
        {
            this.approvals = new HashSet<approval>();
            this.bookingstatus = new HashSet<bookingstatu>();
        }
    
        public int requestid { get; set; }
        public string employeefirstname { get; set; }
        public string employeelastname { get; set; }
        public string employeeemail { get; set; }
        public Nullable<int> employeeid { get; set; }
        public string reasonfortravel { get; set; }
        public Nullable<bool> flightneeded { get; set; }
        public Nullable<bool> hotelneeded { get; set; }
        public string departurecity { get; set; }
        public string arrivalcity { get; set; }
        public Nullable<System.DateTime> departuredate { get; set; }
        public Nullable<System.TimeSpan> departuretime { get; set; }
        public string additionalinformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval> approvals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookingstatu> bookingstatus { get; set; }
        public virtual employee employee { get; set; }
    }
}
